---
- hosts: all

  vars:
    test: "{{ ansible_distribution }}"

  pre_tasks:
    - name: Install OS Packages
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - ubuntu-restricted-extras
        - vlc
        - tlp
        - tlp-rdw

  roles:
    - gnome-desktop
    - google-chrome
