---
- name: Configure various applications
  hosts: localhost
  tasks:
    - name: Install Google Chrome
      import_role:
        name: google-chrome

    # Note that on new laptops there are few things to consiter:
    # 1. Disable UEFI Secure boot or sign the virtualbox modules.
    # See this link for further reading - https://stegard.net/2016/10/virtualbox-secure-boot-ubuntu-fail/
    # 2. Ensure virtualization is enabled from BIOS/UEFI
    - name: Install Virtualbox
      import_role:
        name: virtualbox
      vars:
        virtualbox_version: 5.2
        virtualbox_group_members:
          - root
          - "{{ lookup('env','USER') }}"
      become: true

    - name: Install Vagrant
      import_role:
        name: vagrant
      vars:
        vagrant_version: 2.0.1


