---
- name: Configure vim
  hosts: localhost
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: true

    # https://itsfoss.com/vim-8-release-install/
    - name: Add ppa:jonathonf/vim to install latest vim
      apt_repository:
        repo: 'ppa:jonathonf/vim'
        state: present
      become: true

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - vim-gtk3
      become: true

    - name: Clone Vundle repo
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim

    - name: Check if vimconf was cloned
      stat:
        path: ~/vimconf
      register: vimconf_is_cloned
      changed_when: false

    - name: Clone vimconf repo
      git:
        repo: https://github.com/bboykov/vimconf.git
        dest: ~/vimconf
      when: vimconf_is_cloned.stat.exists == false

    - name: Source vimconf in vimrc
      blockinfile:
        dest: ~/.vimrc
        marker: "\" {mark} Source vimconf ANSIBLE MANAGED BLOCK"
        block: |
          source ~/vimconf/main.vim
        create: yes

    - name: Run vim +PluginInstall +qall after sourcing vimconf
      command: >
        vim +PluginInstall +qall
      when: vimconf_is_cloned.stat.exists == false

    - name: Run vim +PluginClean +qall to remove unused plugins
      command: >
        vim +PluginClean! +qall

    - name: Run vim +PluginUpdate +qall to update plugins
      command: >
        vim +PluginInstall +qall
