---
- name: Show date
  gsettings:
    schema: org.gnome.desktop.interface
    key: clock-show-date
    value: "true"

- name: Never Auto-run with Removable Media
  gsettings:
    schema: org.gnome.desktop.media-handling
    key: autorun-never
    value: "true"

- name: Set Close Window Shortcuts
  gsettings:
    schema: org.gnome.desktop.wm.keybindings
    key: close
    value: "['<Alt>q', '<Alt>F4']"

- name: Sort Directories First
  gsettings:
    schema: org.gnome.nautilus.preferences
    key: sort-directories-first
    value: "true"

- name: List Folder View
  gsettings:
    schema: org.gnome.nautilus.preferences
    key: default-folder-viewer
    value: "list-view"


