# Main playbook to run them all
---
- name: Check ansible version play
  hosts: localhost
  vars:
    required_ansible_version: "2.4.1.0"

  tasks:
    - name: "Fail if current Ansible version less than {{ required_ansible_version }}"
      fail:
        msg: |
          Ansible verison is {{ ansible_version.full }}. This playbook requires Ansible {{ required_ansible_version }} or greater
      when: ansible_version.full < required_ansible_version

- import_playbook: system.yml
- import_playbook: terminal.yml
- import_playbook: apps.yml
- import_playbook: desktop.yml

