# WIP - rework my terminal env (replace shell.yml)
---
- name: Configure the terminal environment
  hosts: localhost
  tasks:
    - name: Add ppa:jonathonf/vim to install latest vim
      apt_repository:
        repo: 'ppa:jonathonf/vim'
        state: present
      become: true

    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # 1h
      become: true

    - name: Install packages via APT
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - vim
        - vim-gtk3
        - default-jdk # rhysd/vim-grammarous depends on java
        - xclip
        - xsel
        - tmux
        - todotxt-cli
        - bash-completion

    - name: Install packages with PIP
      pip:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - grip # prereq for vim-markdown-preview plugin

    - name: Check if dotfiles repo has been cloned
      stat:
        path: $HOME/dotfiles/
      register: is_dotfiles_cloned
      changed_when: false

    - name: Clone dotfiles repo
      git:
        repo: https://github.com/bboykov/dotfiles.git
        dest: $HOME/dotfiles
      register: clone_dotfiles_repo
      when: is_dotfiles_cloned.stat.exists == false

    - name: Run dotfiles makesymlinks script
      shell: >
        cd ~/dotfiles && ./makesymlinks.sh
      args:
        executable: /bin/bash
      when: clone_dotfiles_repo.changed

    - name: Check if vim-plug has been installed
      stat:
        path: $HOME/.vim/autoload/plug.vim
      register: is_vim_plug_installed
      changed_when: false

    - name: Clone base16-shell repo
      git:
        repo: https://github.com/chriskempson/base16-shell.git
        dest: ~/.config/base16-shell

    - name: Check if tmux TPM repo is present
      stat:
        path: ~/.tmux/plugins/tpm
      register: tmux_tpm_repo_is_present
      changed_when: false

    - name: Clone tmux TPM repo
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
      when: tmux_tpm_repo_is_present.stat.exists == false

    - name: Install vim-plug
      shell: |
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        executable: /bin/bash
      when: is_vim_plug_installed.stat.exists == false

    - name: Install plugins with vim-plug - vim +PlugInstall +qall
      command: |
        vim +PlugInstall +qall
      when: is_vim_plug_installed.stat.exists == false

    - name: Update plugins with vim-plug - vim +PlugUpdate +qall
      command: |
        vim +PlugUpdate +qall


    - name: Clone liquidprompt repo
      git:
        repo: https://github.com/nojhan/liquidprompt.git
        dest: ~/liquidprompt

